### ISSUE TITLE
Consider a better name?

### ISSUE THREAD

**Issue by dimaqq** [beeware/voc#587]
Is it just me, or is VOC immediately associated with slavery / private army as much as global commerce / international company funded by private capital?

Could there perhaps be a better name?

**Comment by DemiMarie** [comment]
@dimaqq I agree.

**Comment by eliasdorneles** [comment]
As one data point: personally, I don't have that association at all, mostly because when I learnt about Dutch East India Company in school, it was never referred to its Dutch name nor its acronym.

The C in VOC for me will always stand for Compiler. :)

Vanguard Obscure Compiler
Virtuous Output Compiler
Viable Okay Compiler
Very Odd Compiler
Various Objects Compiler
Verbose Obsessive Compiler
...
