### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by JustineUgo** [beeware/voc#973]
I was following tutorial 0
I made my example.py and wrote 

> print("Hello world!")

I then compiled it with voc into a java class file using

> voc -v example.py

When I tried running it using 

> java -classpath ../voc/dist/python-java-support.jar;. python.example

It showed this error 

> Error: A JNI error has occurred, please  check your installation and try again 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/python/types/Module has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I understand that the java class file has been compiled by java version 11 and I'm try to run it with java version 8.
I'm using jdk1.8.0_221
AND jre1.8.0_221
And 

> ant -version

`Apache Ant(TM) version 1.10.6 compiled on May 2019`

Can you help me here. Can I compile the java class file with java version of 8 instead of java11

**Comment by freakboy3742** [comment]
Thanks for the report! 

VOC-generated code *should* be compatible with every JVM back to Java 6; however, Java isn't *forward* compatible. So - if you're using a a JAR file compiled with Java 11, you can't run it with Java 8; but you can run Java 8-compiled JARs with Java 11.

So - how did you obtain the Python support JAR? Did you compile it yourself, or did you obtain it from someone else? If you obtained it from someone else, it's possible they compiled it with Java 11, which would make it incompatible for your use.

**Comment by JustineUgo** [comment]
Thanks for the quick reply. 
If I'm correct the JAR file is compiled with this command 

> ant Java

I did compile the JAR file while java8 was installed on my computer 
Or am I missing something. Thanks

**Comment by JustineUgo** [comment]
Sorry the command was meant to be

> ant java

**Comment by freakboy3742** [comment]
Ah - so you've compiled it yourself and you're getting this error? That's odd...

Is there any chance you have more than one java installed? Or that you have JDK11, but JRE8 installed? To check - do these two commands agree on the version?:
```
javac -version
java -version
```

**Comment by JustineUgo** [comment]
That was the case earlier.
I has JDK11 and JRE8.
I uninstalled them and installed  both JDK8 AND JRE8. I the deleted the JAR file and ran the command again

> ant java

Or should I delete the voc and install it again with

> pip install -e .

**Comment by freakboy3742** [comment]
Ah! That explains it then! 

So - you don't need to delete and re-install VOC; you should only need to rebuild the JAR file. Try running:
```
ant clean
ant java
```
and then re-running the example.

**Comment by JustineUgo** [comment]
Ow. Okay, I'll do that.  If it works I'll post it and then you could close the issue. I'm glad with the way you handled my problem, thank you. You're great!😁👍

**Comment by freakboy3742** [comment]
No problems at all!

If it turns out that that this *is* a fix for your problem, we could possibly fix this for future users. Javac allows you to specify a `-target` argument to specify the version of JVM that the output code will comply to - if VOC's ant file had specified `-target 1.7`, you wouldn't have seen this problem (as the JAR file that was produced would have been compatible with your JRE).

If you feel like trying to contribute to an open source project, see if you can work out how to add that option to the Ant file (for both the Java and Android build targets)!

**Comment by JustineUgo** [comment]
Okay. I'll look into that. I'm new to contributing to open source.  If I follow the guide you made, can I achieve this?

**Comment by freakboy3742** [comment]
Absolutely! We've helped lots of people make their first open source contribution - and we're always eager to help more. If you need any help, just ask!

**Comment by JustineUgo** [comment]
Okay, thanks.  I'll get started with the guide.

**Comment by JustineUgo** [comment]
> ant clean

> ant java

Worked!!!!!!
I'm so excited, what do I need to do, to start contributing, to add the `-target` option to the ANT file

**Comment by freakboy3742** [comment]
🎉 

So - to contribute; the task is to generate a pull request that contains the changes you want to propose to VOC.

There's a few steps to the process; here's a guide to what is involved:

https://thenewstack.io/getting-legit-with-git-and-github-your-first-pull-request/

That tutorial contains a sample project that you can use for practice before you do anything on a "live" project like VOC.

In your case, the change will be a modification to `build.xml`, `build-java.xml`, or `build-android.xml` that adds the `target` flag to the javac compile instruction.

Make the change locally (and test that it works); commit the change to your own branch; and submit that branch as a pull request against the main VOC repository.

If any of this is overwhelming - don't worry - I know there's lots of new terminology here. We're here to help if you get stuck.

You might find it helpful to join our chat room: https://gitter.im/beeware/general - it may be easier to get fast feedback there rather than via comments on a Github ticket

**Comment by JustineUgo** [comment]
Thanks. I'll get started
